version: '3'

services:

  selenium:
    image: selenium/standalone-chrome:3.141.59-lithium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2@sha256:c957a3acb7899597cced35a24fecb64988b398094d82b88212f8e40d2f790991
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2@sha256:df44cab5fb54f4c696907c06424eeb01b073b13c4d3a116ea47c6f5131f2f649
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  webserver:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
      - selenium
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
       - ./airflow/dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  esdata:
    driver: local
