version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  postgresql:
    image: orchardup/postgresql:latest
    environment:
      - POSTGRESQL_USER=airflow
      - POSTGRESQL_PASS=airflow
      - POSTGRESQL_DB=airflow
    expose:
      - "5432"
    networks:
      - elk

  webserver:
    build: py_scraping/
    restart: always
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./py_scraping/app/:/app
      - ./py_scraping/dags/:/root/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - elk

networks:

  elk:
    driver: bridge
